#!/bin/bash

## Set up suffix for adjoint run: "_ad"
#  or leave as "" for forward run
suff=""
build_suff=''

## Set up directories
root_dir=$WORK/sose/MITgcm
exp_dir=$PWD
build_dir=$exp_dir/build$suff$build_suff
code_dir=$exp_dir/code$suff$build_suff

## Opt file architecture specific
#skylake_opt=$computing/optfiles/linux_amd64_ifort+mpi_stampede2_skx
haswell_opt=$exp_dir/linux_amd64_ifort+mpi_ice_nas_haswell

## Use the correct opt file here
build_cmd="$root_dir/tools/genmake2 -rd=$root_dir -mods=$code_dir -optfile=$haswell_opt -mpi"
#tmp="make_junk"$suff".txt"

## Check which run to set up
if [[ $suff == "_ad" ]]
  then
        echo "Preparing adjoint run ..."
elif [[ $suff == "" ]]
  then
        echo "Preparing forward run ..."
else
        echo "Unsure of suffix, exiting ..."
        exit 1
fi

## Build the model in build directory
if [ ! -d $build_dir ]
  then
        mkdir $build_dir
        cd $build_dir
else
        cd $build_dir
        if [ -s Makefile ] ; then
		make clean
	fi
fi

cd $build_dir
echo "Inside dir: "$PWD

echo "Evaluating: "$build_cmd
eval $build_cmd 
echo "Make depend ..."
eval "make depend" 
echo "Making executable ..."
if [[ $suff == "_ad" ]] ; then
  eval "make -j 16 adall" 
else
  eval "make -j 16"
fi
